name: CI CMS starter

on:
  pull_request:
    branches: [ master ]

jobs:
  build-cms-starter:
    uses: cakes-management-system/ci-cd/.github/workflows/build-with-maven.yml@master
    with:
      display-name: Cakes Service
      sonar: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
